### ISSUE TITLE
EdmLibHelpers.GetDynamicPropertyDictionary always returns null

### ISSUE THREAD

**Issue by badcommandorfilename** [IharYakimush/comminity-data-odata-linq#10]
https://github.com/IharYakimush/comminity-data-odata-linq/blob/0f6be643092124b29c53edd18bbfd1ec210ec1ad/Community.Data.OData.Linq/OData/Formatter/EdmLibHelpers.cs#L696

This causes BindDynamicPropertyAccessQueryNode to throw a NullReferenceException when BindPropertyAccessExpression tries to access prop.Name. 

Some Filter queries with open types can't be parsed. I believe this issue exists in the official OData package too and relates to https://github.com/OData/WebApi/issues/445

**Comment by IharYakimush** [comment]
Hi,

Fix for "BindDynamicPropertyAccessQueryNode throw a NullReferenceException" already available in package version **1.2.0**. Now it should work with in memory IQuerable, however I am not sure about EntityFramework. 
 
In case of dynamic properties dictionary is null for some of the items, you have to specify null propagation behavior explicitly.
 `.OData(c => c.QuerySettings.HandleNullPropagation = OData.Query.HandleNullPropagationOption.False)`
Absent properties in the dictionary will work with default behavior. You can check details in tests at https://github.com/IharYakimush/comminity-data-odata-linq/blob/develop/Community.Data.OData.Linq.xTests/OpenTypesTests.cs.

Also there are some issues with json representation of dynamic properties in SelectExpand method which I going to investigate later on.

I will close this issue. Please feel free to reopen it or create a new one if it would be needed.

Thanks,
Ihar
