### ISSUE TITLE
substringof isn't working

### ISSUE THREAD

**Issue by flieks** [IharYakimush/comminity-data-odata-linq#21]
it works fine with filter startswith or eq
but with substringof i get 

Microsoft.OData.ODataException: 'An unknown function with name 'substringof' was found. This may also be a function import or a key lookup on a navigation property, which is not allowed.'

**Comment by IharYakimush** [comment]
I am not sure that "substringof" is a valid function for OData V4 protocol.

Check the http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part2-url-conventions/odata-v4.0-errata03-os-part2-url-conventions-complete.html#_Toc444868693 to see list of available functions and query syntax samples.

**Comment by flieks** [comment]
thanks , you are right, i was using V4 where it is "expands"
