### ISSUE TITLE
Use MS.Ext.DI.Abstractions instead of MS.Ext.DI

### ISSUE THREAD

**Issue by ysmoradi** [IharYakimush/comminity-data-odata-linq#23]
Not all projects are using the default implementations of MS.Ext.DI.Abstractions which is MS.Ext.DI
For example, we're using [Autofac.Extensions.DependencyInjection](https://www.nuget.org/packages/Autofac.Extensions.DependencyInjection/)

**Comment by IharYakimush** [comment]
changes are available in NuGet version 1.4.2

**Comment by ysmoradi** [comment]
Thanks (:
