### ISSUE TITLE
Configuration of MaxExpansionDepth

### ISSUE THREAD

**Issue by nmbatalha** [IharYakimush/comminity-data-odata-linq#28]
We're making use of the Library version 1.4.0.0 and we're having some issues with some OData queries which have an expand depth higher than 2.

**_"The request includes a $expand path which is too deep. The maximum depth allowed is 2. To increase the limit, set the 'MaxExpansionDepth' property on EnableQueryAttribute or ODataValidationSettings, or set the 'MaxDepth' property in ExpandAttribute"_**

My question in this regards is if ( and how ) is it possible to override the default value of 2, which seems to be set by default on ODataSettings.cs (ODataValidationSettings class).

Can you please help us find a way ?

Thank you very much.
Great work.

Best regards,
Nuno Batalha

**Comment by IharYakimush** [comment]
Try to increase the limit in validation settings when you initialize OData query
```
items.OData(settings => settings.ValidationSettings.MaxExpansionDepth = 3)
```

**Comment by nmbatalha** [comment]
Awesome, works perfectly. Thank you very much for the support.
