### ISSUE TITLE
how works $filter in $expand ?

### ISSUE THREAD

**Issue by ChristopherLenz** [IharYakimush/comminity-data-odata-linq#29]
Hello,

we use this project since some weeks. It workds great :thumbsup:

No we encountered one issue.

**Given is following architecture**

```
        class MyClassA
        {
            [Key]
            public string String { get; set; }

            public List<MyClassB> Subs { get; set; }
        }

        class MyClassB
        {
            [Key]
            public int Integer { get; set; }
        }
```

It looks like it is not possible to assign following **odata**:

`$filter=String eq 'A'&expand=Subs($filter=Integer eq 1`

Thanks in advance

**Comment by IharYakimush** [comment]
It should work, check https://github.com/IharYakimush/comminity-data-odata-linq/blob/develop/Community.Data.OData.Linq.xTests/ExpandTests.cs line 129.

What exception you got when trying this query ? 
How you apply this query (code sample is needed) ? 
What nuget package versions you use ?

**Comment by ChristopherLenz** [comment]
ahh okay I see. If I want to filter the "expands" I need to use the functions **SelectExpand()** or **SelectExpandAsQueryable()**. If I do this, I lose the **generic type**, which I have, while using **Filter()**, **OrderBy()** and so on. This means there is no other way?

```
        [TestMethod]
        public void SubLevelFilterTest()
        {
            var odataQuery = GetSampleData().OData();
            odataQuery = odataQuery.Filter("String eq 'A'");

            // This is what I used until now; good result
            var serializeCorrect = JsonConvert.SerializeObject(odataQuery);

            // this is what I have to do to make us of the expand-filter?
            IQueryable<ISelectExpandWrapper> collection = odataQuery.SelectExpandAsQueryable("Subs", "Subs($filter=Integer eq 1)");
            var serializeWrong = JsonConvert.SerializeObject(collection);
        }

        private static IQueryable<MyClassA> GetSampleData()
        {
            return new List<MyClassA>()
            {
                new MyClassA()
                {
                    String = "A",
                    Subs = new List<MyClassB>() {{new MyClassB() {Integer = 1}}, {new MyClassB() {Integer = 2}}, {new MyClassB() {Integer = 3}}, {new MyClassB() {Integer = 4}}}
                },
                new MyClassA()
                {
                    String = "B",
                    Subs = new List<MyClassB>() {{new MyClassB() {Integer = 1}}, {new MyClassB() {Integer = 2}}, {new MyClassB() {Integer = 3}}, {new MyClassB() {Integer = 4}}}
                }
            }.AsQueryable();
        }
```

**Comment by IharYakimush** [comment]
If you need only json representation, you can add package `Community.OData.Linq.Json`, so 

```
IEnumerable<ISelectExpandWrapper> collection = GetSampleData().OData().Filter("String eq 'A'").SelectExpand("String", "Subs($filter=Integer eq 1)");            
            string result1 = collection.ToJson().ToString();
```

Using expand and saving generic type is not possible. If saving generic type is mandatory, you can try
```
MyClassA[] array = GetSampleData().OData().Filter("String eq 'A'").ToArray();
            foreach (MyClassA item in array)
            {
                item.Subs = item.Subs.AsQueryable().OData().Filter("Integer eq 1").ToList();
            }

            string result2 = JsonConvert.SerializeObject(array);
```
however I would not recommend second option, because in case of real data source it might lead to fetching a lot of data from it.

**Comment by ChristopherLenz** [comment]
Hi,

thanks. I gave it a try. but it takes forever.

I extended the test this way:

- source: 2000 instead of 2 MyClassA instances
- filtered: 1000 instead of 1 MyClassA instances

If I do following I get extreamly different execution-times

`OData().SelectExpand(select, expand).ToJson().ToString()`

- expand: "Subs" --> 10 seconds
- expand: "Subs($filter=Integer eq 1)" --> 157 seconds

**Comment by IharYakimush** [comment]
ensure that you pre-load Subs (MyClassB) from data source instead of lazy loading

**Comment by ChristopherLenz** [comment]
This was without a datasource behind. This was a pre-generated list in a unit-test

**Comment by IharYakimush** [comment]
Hi @ChristopherLenz, I added unit tests for performance and not able to reproduce the issue. Please check commit above and verify that we are doing the same.

**Comment by ChristopherLenz** [comment]
> Hi @ChristopherLenz, I added unit tests for performance and not able to reproduce the issue. Please check commit above and verify that we are doing the same.

Okay I have to admit that I forgot an important information... My benchmarks were executed multiple times. So with one iteration I get roughly 3000ms for SelectExpand() --> ToJson() with 2000 items.
This is similar to your test.

Thanks for all the help, but this is too slow for my use case. If I find an performance-improvement I will let you know
