### ISSUE TITLE
TimeZoneInfoHelper always uses local timezone which leads to issues filtering by DateTimeOffset

### ISSUE THREAD

**Issue by sshukurov** [IharYakimush/comminity-data-odata-linq#41]
`TimeZoneInfoHelper` is an internal class without any means to influence it from outside the library, and it always returns the local timezone:
![image](https://user-images.githubusercontent.com/36232686/147837903-56c64406-e3ab-4572-9e5f-972ec2361155.png)

In our code we are using an OData filter expression like: `SomeProperty ge 2014-01-01T00:00:00.0000000Z`, the right hand-side of which is represented as a `DateTimeOffset` value under the hoods. The library processes that value by converting it to the local timezone and throwing away any timezone information like so:
![image](https://user-images.githubusercontent.com/36232686/147837836-ead3c769-75bc-4f3e-b577-daa1088859fb.png)

I attempted to modify the source and specify `DateTimeKind.Local` for the `DateTime` value returned above, but that didn't bring about any change. The actual dataset in our case contains values for the relevant property with `DateTimeKind.Utc`.

**Comment by sshukurov** [comment]
I see the desired correct behavior if I change the library to explicitly return values in UTC like so:
![image](https://user-images.githubusercontent.com/36232686/147838599-bf39a107-4fed-4ecf-9081-a3980b4794a6.png)

I understand that's not a generally workable solution, just fyi.

**Comment by sshukurov** [comment]
Looks like specifying `Local` kind as I mentioned above didn't produce the expected results for me because two `DateTime` structures which refer to the same point in time but have different kinds are NOT treated equal!

**Comment by IharYakimush** [comment]
Hi @sshukurov , starting from version 2.1.0 you can set default time zone info `.OData(c => c.QuerySettings.DefaultTimeZone = TimeZoneInfo.Utc)`.

**Comment by sshukurov** [comment]
Hi @IharYakimush, thank you so much for delivering a prompt fix for this 👍
