### ISSUE TITLE
InvalidOperationException: The entity does not have a key defined

### ISSUE THREAD

**Issue by wadebee** [IharYakimush/comminity-data-odata-linq#5]
By convention the entity key property is Id. How do I modify my EntityType EDM registration to reflect my domain key (eg: builder.EntityType.HasKey(t => t.MyDomainKey)?

**Comment by wadebee** [comment]
Ok, I figured this out looking at the source code.  Looks like the IQueryable.OData extension method allows you to pass in an IEdmModel. I declared my types (with custom keys) and passed it in. Query filtered as expected.

Thanks, Wade

**Comment by IharYakimush** [comment]
Hi Wade,

Also you can use `System.ComponentModel.DataAnnotations.KeyAttribute` to define an entity key.

`using System.ComponentModel.DataAnnotations;

    public class SampleWithCustomKey
    {       
        [Key]
        public string MyDomainKey { get; set; }

        public DateTime DateTime { get; set; }
    }`

Thanks,
Ihar

**Comment by mehdipanjwani-ains** [comment]
[Key] attribute works. But when scaffolding (db first) the entity model is recreated automatically which reverts the manual changes.

Is it possible to specify the key during OnModelCreatingPartial?

```
partial void OnModelCreatingPartial(ModelBuilder modelBuilder) {
    modelBuilder.Entity<SampleWithCustomKey>().HasKey(x => x.MyDomainKey);
}
```
